exp: 
  backbone: mit_b3

dataset:
  root_dir: /home/zexi/ddd17
  name_list_dir: datasets/ddd17
  num_classes: 6
  crop_size: 512
  resize_range: [512, 2048]
  rescale_range: [1, 1]
  ignore_index: 255

train:
  split: train_aug
  samples_per_gpu: 3
  max_iters: 50000
  eval_iters: 5000
  log_iters: 50

val:
  split: val

optimizer:
  type: AdamW
  learning_rate: 1e-5
  betas: [0.9, 0.999]
  weight_decay: 0.01

scheduler:
  warmup_iter: 0
  warmup_ratio: 1e-6
  power: 1.0